timdorr/tesla-api

- apiary.apib
> API Docs Update

- .travis.yml
- lib/tesla_api/stream.rb
Tesla API provides 4 new signals in stream endpoint
as "documented" in the Go wrapper ([github.com/jsgoecke/tesla/stream.go](https://github.com/jsgoecke/tesla/blob/f6fbd0f92e466e64c5d2bf4e2fdf0968f18f3e4c/stream.go))
> New signals in stream

- apiary.apib
Replaced ?? with all the values I've determined for charging_state. Also added a few more values that are returned related to the user set limit and the charge port.
> Added more values with meanings

- apiary.apib
- lib/tesla_api/vehicle.rb
- spec/cassettes/vehicle-activate_speed_limit.yml
- spec/cassettes/vehicle-clear_speed_limit_pin.yml
- spec/cassettes/vehicle-deactivate_speed_limit.yml
- spec/cassettes/vehicle-set_speed_limit.yml
- spec/lib/tesla_api/vehicle_spec.rb
Closes #71
If someone wants, they can [check my work against the swagger doc in my Java Tesla API Client repo](https://github.com/jonahwh/tesla-api-client/blob/master/swagger.yml#L630-L737)
> [#71] Adds speed limit commands to API Blueprint and Client

- docs/api-basics/authentication.md
Give an example of how to refresh the access token using OAuth 2.0. One could argue that you can look this up online, but I think it could be useful here.
>  Add instructions to refresh the access token.

- lib/tesla_api/vehicle.rb
- spec/cassettes/vehicle-seat_heater_request.yml
- spec/cassettes/vehicle-steering_wheel_heater_request.yml
- spec/lib/tesla_api/vehicle_spec.rb
Adds support in the Ruby library for setting seat heaters and the steering wheel heater.
> Support for seat/steering wheel heater requests

- docs/miscellaneous/endpoints.md
- docs/vehicle/commands/README.md
- docs/vehicle/commands/sentrymode.md
> Add Sentry Mode documentation

- docs/vehicle/commands/climate.md
Not sure what your process is for PRs but let me know if I need to change anything.
> Fixed a typo in the seat heater params description

- docs/miscellaneous/endpoints.md
Adds endpoint description from 3.8.3 update.
> Adds service_data endpoint documentation

- docs/vehicle/optioncodes.md
These are for the Model 3 and Model Y.
> Added 18" Aero Wheels to Option Codes

- docs/vehicle/state/vehiclestate.md
Let me know if this is the correct place for this or if there is a better place for this.
> Adding Display States to Docs

- docs/vehicle/optioncodes.md
> New Model S, X and 3 codes

- docs/vehicle/optioncodes.md
> Some additional model S/X codes

- docs/vehicle/state/vehiclestate.md
Describe fully how to understand the all the two-letter short names for the doors
> Added explaination for all doors

- docs/vehicle/optioncodes.md
As titled. Option code is taken from my vehicle invoice.
> Add 20-inch Gray Performance Wheels for Model 3

- docs/vehicle/optioncodes.md
See:
https://www.reddit.com/r/teslamotors/comments/cu29ff/tesla_api_option_codes_wrong/
https://teslamotorsclub.com/tmc/threads/api-returning-wrong-option-codes.168207/
> Warn about deprecated Option Codes (Fixes #168)

- docs/vehicle/commands/wake.md
> Add implementation tips to wake_up.

- docs/vehicle/commands/valet.md
Add additional details to further explain the use of the Valet Mode API
> Clarify use of Valet Mode API

- docs/README.md
Changed to Model S, 3, X, Y.
Changed 
We currently have documentation for THEIR vehicles
To
We currently have documentation for THESE vehicles
> Added model Y

- docs/vehicle/commands/homelink.md
single t in latitude (laTTitude)
> spelling change

- docs/vehicle/commands/sharing.md
I had to search quite a bit to figure this out. 
Is there a way to figure out the user locale code dynamically? Using the API?
The only solution I can think of is to use GPS to get coordinates and then country and then use a dictionary look up.
> Added resource for locale codes

- docs/vehicle/optioncodes.md
I think that's the code
related: https://teslascout.com/view.php?vin=5YJXCCE29GF018008#container
> Add 20" turbine wheels

- docs/vehicle/optioncodes.md
Hello,
I found a missing code for cyclone wheels
Related: https://teslascout.com/view.php?vin=5YJSA7E26GF121393#container
> Add cyclone code

- docs/vehicle/optioncodes.md
> Add Autopilot code for Model 3

- docs/vehicle/optioncodes.md
See https://teslamotorsclub.com/tmc/threads/autopilot-options-on-2018-inventory-apfb-and-apbs.149574/
> Add description about FSD

- docs/vehicle/optioncodes.md
The right code is `PPMR`, already present on the list
related: https://teslascout.com/view.php?vin=5YJ3E7EB6KF222936
> remove wrong code

- docs/vehicle/optioncodes.md
```
AF00	Air Filter	Standard air filter, NO Air Ionizer
AU3P	Sound Studio Package	Premium audio package
AUF1	AUDIO_FIRMWARE_OPTION	Premium Speakers Enabled
BC3R	Brake Calipers	Red brake calipers
BG32	BADGE	Performance AWD Badge
BT42	Model 3 Performance update for 2021 model year includes a new 82kwh battery (code BT42), up from the previous 75kwh .	
CH15	Chargers	48 Amp Charger Hardware (REEU/REAP) with Busbar
CONL	Country Description	Netherlands
CPF1	CONNECTIVITY_FIRMWARE_OPTION	Premium Connectivity Enabled
DV4W	Motor	Dual Motor
FC02		
FD00		
FG31	Fog Lamps	Base Fog lights …
```
> Latest 2021 M3P (end of april)

- docs/vehicle/optioncodes.md
Added in IBE00 (Wood Décor) and IBC00 (Carbon Fiber Décor)
> Added Model S Décor Option Codes

- docs/vehicle/optioncodes.md
Model3 NL 04/29/2021
VIN: 5YJ3E7EC0MF96****
Code  Category  Description
AD15  Adapter  J1772
AF00  Air Filter  Standard air filter, NO Air Ionizer
APFB  Autopilot Firmware  Standard Autopilot Firmware
APH4  Drivers Assistance Package  Autopilot 3.0 Hardware
AU3P  Sound Studio Package  Premium audio package
AUF1  AUDIO_FIRMWARE_OPTION  Premium Speakers Enabled
BC3R  Brake Calipers  Red brake calipers
BG32  BADGE  Performance AWD Badge
BT42  82 kWh (Model 3)  
CDM0  CHADEMO  CHAdeMO no
CH15  Chargers  48 Amp Charger Hardware (REEU/REAP) with Busbar
CONL  Country Description  Netherlands
CPF1  CONNECTIVITY_FIRMWARE_OPTION  Premium Connectivity Enabled
DRLH  Drive Orientation  Left Hand Drive
DV4W  Motor  Dual Motor
FC02    
FD00    
FG31  Fog Lamps  Base Fog lights (RENA)
FGF1 …
> Changes to TM3P 2021 EU spec (28.04.2021 biuld)

- docs/vehicle/optioncodes.md
AF00	Air Filter	Standard air filter, NO Air Ionizer
AU3D	Sound Studio Package	Reduced Audio Package
AUF2		
BC3B	Brake Calipers	Black brake calipers
BG30	BADGE	No Badge
BTF0		
CH15	Chargers	48 Amp Charger Hardware (REEU/REAP) with Busbar
CONL	Country Description	Netherlands
CPF1	CONNECTIVITY_FIRMWARE_OPTION	Premium Connectivity Enabled
DV2W	Motor	Single Motor
FC01	Front Console	Inductive Phone Charger
FG3B	FOGLAMP	Fog Lamp Cover
FGF0	FOG_LAMP_FIRMWARE_OPTION	Fog Lamps Disabled
FM3S	Performance Package (Model3)	Semi de-rated firmware
GLCN	GLIDER	Giga3 Model 3
HL32		
HM30	Teck …
> m3 china update

- docs/vehicle/optioncodes.md
ModelY NL 07/22/2021
VIN: LRWYGCEK1MC***521
AF02	Air Filter	HEPA Filter
AU3P	Sound Studio Package	Premium audio package
AUF1	AUDIO_FIRMWARE_OPTION	Premium Speakers Enabled
BC3B	Brake Calipers	Black brake calipers
BG31	BADGE	AWD Badge
BT38	Battery	74 KWh Battery Pack with LG cells
BY01		
CH15	Chargers	48 Amp Charger Hardware (REEU/REAP) with Busbar
CONL	Country Description	Netherlands
CPF0	CONNECTIVITY_FIRMWARE_OPTION	Premium Connectivity Disabled
DV4W	Motor	Dual Motor
FC02		
FD01		
FG31	Fog Lamps	Base Fog lights (RENA)
FGF1	FOG_LAMP_FIRMWARE_OPTION	Fog Lamps Enabled
FM3B …
> MY 2021 China made

- docs/vehicle/optioncodes.md
ModelX US 10/19/2020
VIN: 5YJXCAE2*MF311***
X037	Tech Package - Mirror -YES	Power Folding Mirror
PK00	Parking Sensors	No Parking Sensors
RDU4	Rear Drive Unit	Rear small drive unit with electric oil pump
SP00	Security Package	No Security Package
SU03	Suspension	Adaptive Air Suspension
CW02	Weather Package	Cold Weather Package
COUS	Country Description	United States
IDBA	Interior Decor	Black Ash interior décor
X001	Teck Package - Liftgate	Override: Power Liftgate
MI04	Project/Program Code	Pedestrian Protection
RBMB	Rear Brakes Assembly	Rear Brake Mando Black
SC04	Supercharge Hardware	Pay as you go Supercharging
BTXA	Battery	18650J2 Battery Cell
X040	HD Radio	No DAB Radio …
> MX2020.09 code added

- docs/vehicle/optioncodes.md
ModelS NL 08/08/2020
VIN: 5YJSA7E49LF40****
CW02	Weather Package	Cold Weather Package
X019	Rear Spoiler	Rear Carbon Fiber Spoiler
X001	Teck Package - Liftgate	Override: Power Liftgate
X037	Tech Package - Mirror -YES	Power Folding Mirror
PK00	Parking Sensors	No Parking Sensors
PP01	Pedestrian Protection	Ped Pro R127 Compliant
RDU2	Rear Drive Unit	Large Drive Unit Performance
SU03	Suspension	Adaptive Air Suspension
FBBR	Front Brake Assembly	Front Brake Brembo Red
S42W	Seat	White Plenum M3 Seats
MI04	Project/Program Code	Pedestrian Protection
SC04	Supercharge Hardware	Pay as you go Supercharging
WR02	WRAP	Wrap 2 (Tilburg bound)
AU01	Sound Studio Package	Sound Studio Package …
> MS 08/2020

- docs/vehicle/optioncodes.md
> Korea / Asia added

- docs/vehicle/commands/charging.md
Commands:
- set_scheduled_charging
- set_scheduled_departure
> Description of 2 new charging commands

- lib/tesla_api/vehicle.rb
Implementation of the 3 commands:
- set_charging_amps
- set_scheduled_charging
- set_scheduled_departure
> Implementation of 3 new charging commands

- docs/vehicle/optioncodes.md
COCA replaced COUS on my Model 3 on October 21st.
> Added COCA = Country: Canada

- docs/vehicle/commands/charging.md
Detail how the Tesla app sets this argument
(and fix another copy'n'paste typo)
> Detail set_scheduled_departure.enable value

- lib/tesla_api/vehicle.rb
- spec/cassettes/vehicle-set_charging_amps-10.yml
- spec/lib/tesla_api/vehicle_spec.rb
Changed argument from `amps` to `charging_amps` and added spec
> Fixed set_charging_amps + spec

- docs/vehicle/optioncodes.md
Model3 NL 10/31/2021
VIN: LRW3**FA*MC422***
AF00	Air Filter	Standard air filter, NO Air Ionizer
AU3D	Sound Studio Package	Reduced Audio Package
AUF2		
BC3B	Brake Calipers	Black brake calipers
BG30	BADGE	No Badge
BTF1		
CH15	Chargers	48 Amp Charger Hardware (REEU/REAP) with Busbar
CONL	Country Description	Netherlands
CPF0	CONNECTIVITY_FIRMWARE_OPTION	Premium Connectivity Disabled
DV2W	Motor	Single Motor
FC02		
FG3B	FOGLAMP	Fog Lamp Cover
FGF0	FOG_LAMP_FIRMWARE_OPTION	Fog Lamps Disabled
FM3S	Performance Package (Model3)	Semi de-rated firmware
GLCN	GLIDER	Giga3 Model 3
HL32		
HM30 …
> new model 3 standard+ options

- docs/miscellaneous/endpoints.md
Check out VEHICLE_CHARGE_HISTORY
> Updated endpoints of 4.4.0

- docs/vehicle/optioncodes.md
AF02	Air Filter	HEPA Filter
AU3P	Sound Studio Package	Premium audio package
AUF1	AUDIO_FIRMWARE_OPTION	Premium Speakers Enabled
BC3B	Brake Calipers	Black brake calipers
BG31	BADGE	AWD Badge
BT42		
BY01		
CH16	Chargers	48 Amp Charger Hardware (RENA) with Busbar
COUS	Country Description	United States
CPF1	CONNECTIVITY_FIRMWARE_OPTION	Premium Connectivity Enabled
DV4W	Motor	Dual Motor
FC02		
FCH2		
FD00		
FG31	Fog Lamps	Base Fog lights (RENA)
FGF1	FOG_LAMP_FIRMWARE_OPTION	Fog Lamps Enabled
FM3B	Performance Package (Model3)	Base Firmware
GLFR	Assembly	Fremont Assembly
HL31	Head …
> MY 11/2021 US spec

- docs/vehicle/state/vehiclestate.md
TPMS was added to the `vehicle state` endpoint.
> Update to include TPMS attributes

- docs/vehicle/commands/climate.md
- env_ownerapi_endpoints.json
* Update endpoints file to the latest version (on par with Tesla App v4.11.1-1195)
* Mostly features insurance or non-vehicle related. (No documentation needs to be updated so far)
* Fix formatting in [`Climate.md`](https://github.com/timdorr/tesla-api/blob/master/docs/vehicle/commands/climate.md)
* POST request string being too big, due to it using a single hashtag instead of two. ([Vehicle Seat Cooler Request](https://github.com/timdorr/tesla-api/blob/master/docs/vehicle/commands/climate.md#post-api1vehiclesidcommandremote_seat_cooler_request))
> Rebase/remove previous commit history to clean up. (as per request by repo owner)
> Update endpoints + markdown error fix 🛠️

- docs/vehicle/state/climatestate.md
Adding some lines to the documentation of climate state. Found via teslajsonpy logs.
> fix: Updated climate state json

- docs/energy/state.md
First PR against the API library so please let me know if you would like any further detail for future submissions.
> Document backup_time_remaining endpoint

- docs/energy/state.md
using the SITE_TARIFF endpoint.
Maybe a bit long for inclusion here, so I may need to simplify but keep the structure.
> Update of api/1/energy_sites/{site_id}/tariff_rate

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to v4.14.4-1455 on par with the Tesla App
> Only one small change regarding the lootbox, nothing major/no changes to documentation needed.
> Update ownerapi_endpoints.json to 4.14.4-1455 🔗

- docs/vehicle/state/misc.md
Looks like I found how the app is requesting a newer version's release notes!
Made the necessary modifications to @core-hacked's already contributed docs.
Here's a response from a request with `staged=true` appended:
```json
{
"response": {
"release_notes": [
{
"title": "Camera-Based Detection",
"subtitle": "Sentry Mode Improvements",
"description": "When Camera-Based Detection is enabled, Sentry Mode will use the vehicle’s external cameras in addition to vehicle sensors to detect a security event while parked. If disabled, the vehicle will only save clips to the USB drive if a physical threat is detected. To adjust, tap Controls > Safety > Sentry Mode > Camera-Based Detection.",
"customer_version": "2022.44.2",
"image_url": "https://vehicle-files.teslamotors.com/release_notes/{id}?__gda__ …
```
> Add staged=true to release_notes endpoint docs

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to `v4.16.0-1522` on par with the Tesla App
> Notes: mostly changes around the `bff (backend-for-frontend)` endpoints. Changes to names eg. service => support and some additions to this. No major changes, nothing needs to be updated as of now.
> Update `ownerapi_endpoints.json` to v4.16.0-1522

- ownerapi_endpoints.json
- Update the `ownerapi_endpoints.json` file to the newest one on par with the Tesla App v4.17.0-1566.
> Notes: Unrelated changes to this project, only insurance endpoints and stuff. No vehicle/command endpoints or breaking changes.
> Update `ownerapi_endpoints.json` to v4.17.0-1566 on par with Tesla App

- docs/api-basics/users.md
> Document "keys" endpoint used for BLE keys and alike

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to v4.19.5-1667 on par with mobile app.
> Notes: No breaking changes, just BFF (backend-for-frontend) endpoint changes.
> Update `ownerapi_endpoints.json` to v4.19.5-1667

- docs/vehicle/commands/softwareupdate.md
- Updated the response which the software update scheduling gives to the one that is correct.
---
```json
{
"expected_duration_sec": 3000,
"reason": "",
"result": true,
"scheduled_time_ms": 1685735308001,
"status": "scheduled",
"warning_time_remaining_ms": 120000
}
```
```json
{
"reason": "",
"result": true
}
```
> Update Software Update Response

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to `v4.21.5-1749` on par with mobile app]
> No breaking changes. Just BFF & mobile-app endpoint changes.
> Update `ownerapi_endpoints.json` to v4.21.5-1749

- docs/vehicle/commands/climate.md
- docs/vehicle/state/data.md
Added bioweapon mode to vehicle state, and added manual_override to set_bioweapon_mode command
> Add bioweapon mode

- docs/energy/commands.md
I MITM'd the Tesla app using a custom CA that I loaded onto my iPhone and saw that this is the format of the request that was sent. I then tested it out on my Powerwall 2 by updating the golang lib I'm using to interact with the Tesla API. I have a separate open PR for that here: https://github.com/bogosj/tesla/pull/140
I am likely to make more PR's for other undocumented Powerwall functionality if this PR is accepted.
> Document toggling Powerwall Storm Watch mode
