- apiary.apib
Starting auto conditioning just turns on climate control. It may or may not use AC, depending on your settings.
> AC ≠ Auto Conditioning

- Rakefile
- lib/tesla_api.rb
- lib/tesla_api/autopark.rb
- lib/tesla_api/vehicle.rb
- lib/tesla_api/version.rb
- tesla_api.gemspec
Adds a `start_autopark` method on `TeslaApi::Vehicle`. Takes in a block that gets two args: `msg_type` and `message`.
Here's some really basic code that gets things started:
```ruby
vehicle = client.vehicles.first
vehicle.start_autopark do |msg_type, message| 
p msg_type, message 
end
```
> Autopark support in gem

- lib/tesla_api/client.rb
- spec/cassettes/client-login.yml
- spec/lib/tesla_api/client_spec.rb
`/oauth/token` provides `expires_in: <seconds>` and `created_at: <timestamp>`
so I added a method `.expired?` in `TeslaApi::Client`.
Inspired from behavior of the [intridea/oauth2](https://github.com/intridea/oauth2/blob/master/lib/oauth2/access_token.rb) gem.
Thanks @timdorr !
> Add token expiry status

- apiary.apib
Clarify that the charge port open endpoint can also be used to unlock the charge port
> Charge Port Open Clarification

- apiary.apib
- lib/tesla_api/vehicle.rb
- spec/cassettes/vehicle-open_frunk.yml
- spec/cassettes/vehicle-open_trunk.yml
- spec/lib/tesla_api/vehicle_spec.rb
This was a change in the Tesla API sometime around the end of July 2018
> Updates trunk_open to actuate_trunk

- lib/tesla_api/client.rb
- lib/tesla_api/vehicle.rb
It isn't used anywhere in the `Vehicle` class, so seems extraneous. 
It is still accessible from `Vehicle#api`
> Remove email attribute from Vehicle

- lib/tesla_api/client.rb
Fix issue that surfaced on 29 Aug 2018 about 14:44 CDT, resulting in 'Our servers are waiting for a supercharger spot..' html msg instead of json data.  Fix inspired by https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/
Apologies that I haven't spent the time to learn and run and update the test suite successfully, but I did do a 'gem build' of model-s-api with this fix, copied the .gem to my repo, did a 'gem unpack', pointed to it from Gemfile, verified it locally, checked the unpacked gem and tweaked Gemfile into my repo, deployed to heroku, and verified that my website is now collecting my car data again.
Hope this helps!
> Add User Agent headers to requests

- docs/vehicle/optioncodes.md
I went to the Tesla design studio web site and matched up the exterior colors I saw on the site with the option codes here. The web site appears to use a "compositor" API endpoint to retrieve images for the designer based on color (and other options) chosen. I went to the web site and tracked updates to the image href to figure out which of the options changed when I switch colors. I hope this proves useful!
> Add information about option codes corresponding to exterior colors

- README.md
The current link provided links to and outdated/unused apiary.io page.
> updating link for documentation

- docs/vehicle/optioncodes.md
I am using the API and none of the documented model options are available in the "option_codes".  I am seeing "MSO3".  "MDLS", "MDL3", and "MDLX" are not available.  "api_version"=>6
Here are all of the "Option Codes I am getting back from our Model S via the API:  
"option_codes"=>"MS03,RENA,AD02,AU00,BC0B,BS00,BT85,CH00,PPMR,CW00,DRLH,FG01,HP00,HP03,IDPB,IX00,LP00,PA00,PF00,PK01,PS00,PX00,QPMB,RFPO,SC01,SP00,SU01,TM00,TP01,TR00,UTMF,WTTP,WTX1,X001,X003,X007,X011,X014,X021,X025,X027,X028,X031,X037,YF00,COUS",
> Model S seems to show an option code of MS03

- docs/vehicle/state/chargestate.md
Tesla released some updates a few months ago that modifies how the Model 3 behaves in cold weather to address problems some owners were having. One of those changes alters the behavior of the charge port locking/unlocking in cold weather. It looks like the ChargeState response will now tell you if this new mode is enabled or not.
> Update ChargeState response

- docs/vehicle/commands/climate.md
- docs/vehicle/state/climatestate.md
Add documentation for creating a remote steering wheel heater request and update the response that climate state data requests return.
The new key in the climate state response, `remote_heater_control_enabled`, seems to just mirror the `is_climate_on` key.
>  Add remote steering wheel heater requests

- docs/vehicle/optioncodes.md
Seen in this option code string from a Model S 85D:
`MS04,RENA,AU00,BC0B,BS00,BT85,CDM0,CH00,PMSS,CW00,DA01,DRLH,DSH7,DV4W,FG02,HP00,IDHG,IX00,LP00,ME02,PA00,PF00,PI00,PK00,PS01,PX00,QPMG,RFBC,SC01,SP00,SR01,SU01,TM00,TP02,TR00,UTAB,WT19,WTX1,X001,X003,X007,X011,X014,X021,X025,X027,X028,X031,X037,YF00,COUS`
> Add MS04 option code for Model S.

- docs/vehicle/optioncodes.md
Just adding a few option codes from my SR+'s configurator.
Full string is:
```
$PRM30,$MT301,WR01,$DV2W,$PBSB,$MDL3,ZCST,$W38B,$IN3BB,$SC04
```
`WR01` might be 18" aero wheels. Still not able to figure out `ZCST` or `W38B`.
> Adding some option codes from my SR+

- lib/tesla_api/client.rb
- lib/tesla_api/version.rb
- spec/cassettes/client-login.yml
- spec/lib/tesla_api/client_spec.rb
The `refresh_token` that is provided from the OAuth login is not used in the base repository.
I need to be able to request a new `access_token`, but this only works by having the `refresh_token`
available.
> Retrieve refresh_token from the OAuth login

- docs/vehicle/optioncodes.md
Just received my final invoice for my UK Model 3 order and spotted a few option codes not present in the API docs.
> Additional option codes for a UK Model 3

- lib/tesla_api/client.rb
- spec/cassettes/client-login_timeout.yml
- spec/lib/tesla_api/client_spec.rb
Using this awesome gem, we discovered that sometimes API calls fail due to timeout/load related errors on Tesla's API side.
We especially recorded:
- 408 Request Timeout
- 502 Bad Gateway
in maybe 1 in 100 calls.
This pull requests enables the Faraday retry feature and therefore retries any request up to 3 times with a pause of 0.5 seconds between each trial (increasing with a backoff factor 2), if the response code was one of the before mentioned codes.
> Retry request on timeouts

- docs/vehicle/commands/windows.md
At least, on mine, I get the `too_far_from_vehicle` error with 0,0,
but my windows roll up if I give it the vehicle's location.
> lat,lon is required for closing windows.

- docs/vehicle/state/vehiclestate.md
After testing on my Tesla Model LR Dual Motor in Norway, the status for open/closed frunk and trunk is defined by the elements ft and rt
> Update to vehiclestate.md with status for open/closed frunk and trunk

- lib/tesla_api/client.rb
This removes duplicate definitions of the base URL as part of the URLs the client needs to hit. This makes it easier to configure. It's not just more DRY code I actually need to change the URI to a mock API.
Why is this needed?
Normally you wouldn't change a constant (duh!), however in my case I need to remove the constant and reset it (effectively overriding it) to allow me to test this gem in combination with a mock API that we're developing (as a sandbox, which doesn't require you to have Tesla's to develop something and you can't break any Tesla infrastructure). It's our intention as it becomes a bit nicer code that we open source this mock API so people can test against that. We need this PR for that reason.
Unsetting the const and then overriding it is fine with me, but feel free to …
> Use a single BASE_URI

- lib/tesla_api/client.rb
This is the follow up pull request after @timdorr's [comment](https://github.com/timdorr/tesla-api/pull/180#issuecomment-603592250) in #180. This is our use case as mentioned before:
We have a Ruby application which talks to the Tesla API, unfortunately not everyone in the team has a Tesla to test our app with.
That’s why we created an internal mocking server that mimics the Tesla api (to some extend).
Some users in our system connect to a mock backend and some users use the official Tesla end point, all in one codebase, at the same time. That’s why the base URI needs to be dynamic for us.
With this change you can initialize a Api connection with another `base_uri` in the following way:
```ruby
mocked_client = TeslaApi::Client.new(base_uri: "http://localhost/mock")
mocked_client.vehicles …
```
> Add `base_uri` as argument in the contructor

- lib/tesla_api/vehicle.rb
If you use a float it will set the charge limit to 50%
> Charge limit only allows integers

- lib/tesla_api/client.rb
All options to be passed through to the API client (e.g. `proxy`).
> Add client_options param to pass to API client

- lib/tesla_api/stream.rb
Fixes issue #191 
I also added a change to allow the endpoint to be configurable – this would allow me to proxy streams as well as the REST API.
> Set stream protocol to HTTP 1.1

- docs/vehicle/optioncodes.md
I removed `hardware` keyword because hardware is a totally different thing; You can have Autopilot 2 with HW2, HW2.5 or HW3.0
> Update Autopilot & Hardware codes

- docs/api-basics/authentication.md
After some testing I noticed Tesla's new Auth0 endpoints would sometimes return a page of obfuscated javascript.  Watching the requests from the app I noticed the JS evaluated would result in 1-3 requests to `https://auth.tesla.com/TSPD/`.  This would only happen if `User-Agent` was set to a UA that looked like a browser.  After changing it to something obscure that identified the application it worked fine.
> Add note about setting User-Agent during auth

- docs/vehicle/commands/charging.md
Scheduled times can be any value in minutes since midnight local time, even if Tesla apps do not propose it.
> Time is not necessarily a 15min multiple

- docs/vehicle/commands/remotestart.md
I don't know if this is a temporary change, a bug, or there intentionally, but the API no longer seems to require your account password when you remote start the car, and the mobile app doesn't prompt for it.
> Remote start no longer requires password

- lib/tesla_api/client.rb
- spec/cassettes/client-refresh.yml
- spec/lib/tesla_api/client_spec.rb
We noticed that exchanging the SSO token for an `access_token` in the `refresh_access_token` method does not work anymore (and received a 401 when trying to POST to https://owner-api.teslamotors.com/oauth/token).
However, it works perfectly fine if the returned `access_token` is used directly. The only downside is: its only valid for 8 hours (28800 seconds).
> Use SSO access_token directly instead of exchanging it

- docs/api-basics/authentication.md
- docs/vehicle/commands/climate.md
- docs/vehicle/optioncodes.md
Update documentation to fit the API changes regarding the OAuth bearer token, and remove step four, as it has been depracted and add documentation for the ``set_bioweapon_mode`` and ``set_climate_keeper_mode`` endpoints.
> Update Authentication & Climate Documentation 📚

- docs/api-basics/authentication.md
Some details around access token use and refreshing are no longer valid including:
- removal of reference to Step 4 which is missing
- removal of reference to access tokens with region specific prefixes which are no longer relevant
- removal of comment about using Owner API to get a new access token which is no longer required
- calling out that SSO to Owner API access token exchange is no longer required for clarity
> Removed deprecated authentication details

- docs/energy/state.md
I have a Tesla solar system (11.2 kW) with a single Tesla inverter (7.6 kW) and no powerwalls. I do have the Neurio energy monitoring device installed which provides grid export/import (measured) and home consumption (calculated) in the Tesla app. I noticed there wasn't any documentation for some of the endpoints so I figured I'd add them. I specified the response is for a solar panel system without poweralls. Some of the unique data to my system was replaced or obfuscated but the formatting was not changed.
> Solar energy state updates

- ownerapi_endpoints.json
* Update ``ownerapi_endpoints.json`` to v4.14.1-1395
> Notes: No door unlatch endpoint to be seen, maybe door_unlock with a parameter? Needs to be looked at for the new M3/Y feature. Funny enough the old ``env_ownerapi_endpoints.json`` file can now be found in ``tesla.apk/res/raw/..`` It does not seem to have anything new or be different from the ``ownerapi_endpoints.json`` but it's weird tesla re-included it here for no reason.
> Update ownerapi_endpoints.json to v4.14.1-1395

- docs/SUMMARY.md
- docs/api-basics/users.md
- docs/user/data.md
- docs/vehicle/commands/doors.md
- docs/vehicle/commands/misc.md
- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to version 4.14.3-1431, on par with the Tesla App.
- Add two endpoints to the documentation.
- Document `/api/1/users/vault_profile`.
- Document `/api/1/users/feature_config`.
- Split out non-vehicle related endpoints out into a sperate `user` section of the docs.
- These were previously inside `docs/vehicle/misc.md`.
- Remove mentions of retractable/extendable Model X handles. (MX doesn't have door handles, unlike the S)
> On a seperate note, I have found what appears to be the correct way of requesting the door controls for the Palladium (refreshed/post-plaid) Model X. This was mentioned in [#600 Add Support for Model X door controls](https://github.com/timdorr/tesla-api/issues/600). 
However it is untested, as none of the participants have a Palladium …
> Update ownerapi_endpoints, document 2 endpoints, update docs 📚 

- docs/SUMMARY.md
- Add Vehicle Miscellanous Commands to the summary. (`/docs/vehicle/commands/misc.md`)
> Notes: Must have slipped in previous commits. Has gone unnoticed until now. 
The page in gitbook is also not present, it leads to github for some reason. Maybe this PR will fix it?
> EDIT: This PR will fix the absence of the misc page. As seen in the [GitBook Revision](https://tesla-api.timdorr.com/~/revisions/1XeaorGzUAFWwHgEzdRe/vehicle/commands/misc)
> Add misc vehicle commands to summary 📜 

- docs/vehicle/commands/README.md
- docs/vehicle/commands/misc.md
- Add information about what the `remote_boombox` endpoint does. 
- This is the 2022.44.25.1 update's "remote fart" feature for the app. (Emissions Testing Mode via Mobile App)
- Add `./` before `misc.md` page ref, so GitBook does not link to GitHub but rather the page on GitBook itself. 
> This can be removed later, but it seems to fix the wrong page ref.
This also resolves Issue #668
> Update info on what `remote_boombox` is + fix gitbook page ref

- docs/miscellaneous/endpoints.md
- Convert sole link to ``[name](link)`` markdown schema, so it is clickable in gitbook.
1. Alternative to this link could be a gitbook button, so it looks better. 
2. Another alternative is making the page be a link to the endpoints file on GH, instead of it being an almost empty page with already pretty clear/known information.
> Let me know and I will update this PR to be one or the other.
----
```diff
- The latest endpoints file as of version 4.13.3 of the mobile apps is located here: https://github.com/timdorr/tesla-api/blob/master/ownerapi_endpoints.json
+ The latest endpoints file as of version 4.13.3 of the mobile apps is located here:
+ {% page-ref page="https://github.com/timdorr/tesla-api/blob/master/ownerapi_endpoints.json" %}
```
----
```diff
- - [Endpoints …
```
> Make endpoints file link an actual link in GitBook

- .github/workflows/test.yml
Adds Ruby 3.1 and 3.2 to the CI matrix.
Runs green on my fork.
> Adds Ruby 3.1 and 3.2 to the CI matrix

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to v4.18.0-1607 on par with the mobile app.
This update brings new endpoints, which sadly currently, or at least for me, return empty errors. 
```json
"REMOTE_AUTO_STEERING_WHEEL_HEAT_CLIMATE_REQUEST": {
"TYPE": "POST",
"URI": "api/1/vehicles/{vehicle_id}/command/remote_auto_steering_wheel_heat_climate_request",
"AUTH": true
},
"REMOTE_STEERING_WHEEL_HEAT_LEVEL_REQUEST": {
"TYPE": "POST",
"URI": "api/1/vehicles/{vehicle_id}/command/remote_steering_wheel_heat_level_request",
"AUTH": true
},
"NAVIGATION_ROUTE": {
"TYPE": "POST",
"URI": "api/1/vehicles/{vehicle_id}/command/get_active_route",
"AUTH": true
},
```
As mentioned in #684 the two top endpoints are the new steering wheel heater endpoints. So let's re-open the issue.
These return errors for me, but …
> Update `ownerapi_endpoints.json` to v4.18.0-1607

- .github/workflows/formatting.yml
- docs/api-basics/authentication.md
Fixes #699 
Essentially, the `authorize/mfa/verify` endpoint will return a `403` if no `_csrf` is provided in the request. This PR adds intructions on how to do that if users have multi-factor authentication turned on.
> Updates MFA docs

- docs/vehicle/commands/climate.md
- docs/vehicle/commands/misc.md
- ownerapi_endpoints.json
- Document `set_cabin_overheat_protection` endpoint, referenced in issue #701 
- Update `ownerapi_endpoints.json` to v4.19.0-1639 on par with the March 20th, 2023 App Update
- Add notice to `set_vehicle_name` endpoint being removed from the endpoints file. 
- _(Alternatively the docs for this can be removed, but it might return, up to the repo owner)_
> Some new charging related endpoints which return `invalid_command` as of now.
> Removal of one endpoint (mentioned above).
> New energy endpoints.
> More BFF changes.
> Document new endpoint, update `ownerapi_endpoints.json` & add notice about removed endpoint.

- ownerapi_endpoints.json
Updated the ownerapi_endpoints to v4.20.69-1691
Significant changes related to Trip API that allow to plan a trip in the App (ref https://twitter.com/tesla/status/1649178160796139521?s=61&t=5VOmfolc3oSxFcsF7oqGxA) 
- The old `PLAN_TRIP` endpoint has changed to `PLAN_TRIP_CN`
- New `ROADSIDE_STATIC_CONTENT` endpoint
- SERVICE related endpoints `SERVICE_GET_SERVICE_VISIT_AMOUNT_DUE`, `SERVICE_STEPS`, `SERVICE_SAVE_LOCATION`
- Financing related endpoints `FINANCING_GET_ELIGIBLE_DELIVERY_LINKS`, `FINANCING_GET_DELIVERY_LINK`, `FINANCING_SAVE_DELIVERY_LINK_INTENT`
- and others
> update ownerapi_endpoints to v.4.20.69-1691

- docs/vehicle/commands/misc.md
- docs/vehicle/state/README.md
- docs/vehicle/state/chargestate.md
- docs/vehicle/state/climatestate.md
- docs/vehicle/state/data.md
- docs/vehicle/state/drivestate.md
- docs/vehicle/state/guisettings.md
- docs/vehicle/state/vehicleconfig.md
- docs/vehicle/state/vehiclestate.md
- Update information/hint on the `set_vehicle_name` endpoint as it was enabled/added to the app in v4.20.75 & vehicle SW 2023.12+
- Add depraction notice to `chargestate.md`
- Add depraction notice to `climatestate.md`
- Add depraction notice to `drivestate.md`
- Add depraction notice to `guisettings.md`
- Add depraction notice to `vehicleconfig.md`
- Add depraction notice to `vehiclestate.md`
- Add depraction notice to `data.md` which outlines, that the `latest_vehicle_data` endpoint has been depracted in favour of the `vehicle_data` endpoint.
- Add general depraction notice to `README.md` which outlines, that all `data_request` endpoints have been depracted, their information put into the `vehicle_data` endpoint and that the documentation for the different JSON fields still applies.
> …
> Add depraction notices to `data_request` endpoints + update `set_vehicle_name` hint to reflect new changes/app

- docs/vehicle/commands/misc.md
- Update the documentation regarding the `remote_boombox` command.
- Add docs about the body parameter and boombox actions as prep for boombox V2.
> More actions need to be added as Tesla rolls out BBX V2, this is just the preperation for when this change strikes and the app has already been observed to send the post body when the "remote fart button" is clicked.
----
<details>
<summary><h1>New docs/doc update</h1></summary>
Let the car fart remotely on version 2022.44.25.1 and above or use boombox v2 on supported vehicles.
This endpoint does not require a POST body to fart remotely but needs one to use boombox v2.
| Parameter | Example | Description                             |
| :-------- | :------ | :-------------------------------------- |
| action    | 0       | Numerical value …
> Update `remote_boombox` with prep for Boombox V2

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to `v4.22.0-1764` on par with Jun 20th app update.
---
> Notes: 
```json
"TESLA_ELECTRIC_VEHICLES": {
"TYPE": "GET",
"URI": "mobile-app/tesla-electric/vehicles",
"AUTH": true
},
"TESLA_ELECTRIC_SCHEDULE": {
"TYPE": "GET",
"URI": "mobile-app/tesla-electric/unlimited-charging-schedule",
"AUTH": true
},
"TESLA_ELECTRIC_PRICING_DETAILS": {
"TYPE": "GET",
"URI": "mobile-app/tesla-electric/pricing-details",
"AUTH": true
},
```
> These endpoints look interesting. I will look into them, but they are `mobile-app` endpoints. It might just be something about buying the vehicles but yeah.
> Also Vault Profile deletion, which I will address in another PR soon. 🚀 
```json
"USER_RESET_VAULT": {
"TYPE": "DELETE",
"URI": "api/1/users/vault_profile",
"AUTH": true
},
```
> Update `ownerapi_endpoints.json` to `v4.22.0-1764`

- lib/tesla_api/client.rb
`Tesla::Client.new(logger_bodies: true, logger_header: true)` enables Faraday logger
The Faraday client cannot be modified after its constructed; so I believe we need to allow enabling logging middleware during `Tesla::Client.new` constructor.
> Allow Faraday logging

- ownerapi_endpoints.json
- Update `ownerapi_endpoints.json` to v4.23.5-1844 on par with the app.
- Removal of the `PLAN_TRIP_CN` endpoint.
- Addition of a new `VEHICLE_ENERGY_SITES` endpoint.
```jsonc
"VEHICLE_ENERGY_SITES":  {
"TYPE": "GET",
    "URI": "api/1/vehicles/{vehicle_id}/energy_sites",
"AUTH": true
}
```
> Update `ownerapi_endpoints.json` to v4.23.6-1844

- README.md
Deprecated endpoints return 404 code, so the quick example is no more usable.
This commit uses the currently recommended `vehicle_data` endpoint.
> README: Update the example using up-to-date API

- docs/api-basics/vehicles.md
- Document Page parameter in Vehicle listing 
> Relates to #758
> Document Page parameter in Vehicle listing | REL: #758
